x-defaults: &default-settings
  environment:
    # Application Settings
    - APP_NAME=demo   # [ detection | ai_label | continuous | train | frame_insert ]
    - SESSION_NAME=demo       # Any name to identify the session

    # Model and Threshold
    - MODEL_PATH=./models/yolo/model.pt  # Must be inside the 'models/yolo' folder.
    - THRESHOLD=0.5                      # Min: 0.0, Max: 1.0
    - CONSECUTIVE=3                      # Typically 2-5 for stability.

    # Input Settings
    - INPUT_DIR=input/demo       # Must be inside the 'input' folder.

    # Output Settings
    - OUTPUT_SIZE=128,128                # For example: 512,512
    - EXTRACT_BOX=true                   # true/false
    # - PADDING=                         # Optional. Extra padding for image extraction (not fully implemented yet).
    - SHOW_BOUNDING_BOX=false            # Draw bounding boxes on output frames (true/false).
    - CSV_FILE_PATH=output/file.csv      # Path to save the output CSV file.

    # Training-Specific Settings
    - EPOCHS=150                         
    - BATCH=4                            # Valid values: 4, 8, 32, 64, etc. Higher values require more GPU VRAM.
    - MODEL_IMG_SIZE=640
    # File Serving Settings
    - SERVER_USER=${FILE_SERVER_USER}    # Username for file server.
    - SERVER_PASS=${FILE_SERVER_PASS}    # Password for file server.

    # System Environment Settings
    - PYTHONDONTWRITEBYTECODE=1          # Prevent Python from writing .pyc files.
    - PYTHONUNBUFFERED=1                 # Disable Python output buffering.
    - NVIDIA_VISIBLE_DEVICES=all         # Enable all NVIDIA GPUs.
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Required GPU capabilities.

  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
      limits:
        memory: 8g  # Limit container memory usage to 8GB.
  image: lunanightbyte/ml-process:latest
  restart: "no"  # Disable container auto-restart.
  shm_size: '5gb'  # Increase shared memory size to handle large data.
  command: python3 main.py  # Default command to run the application.

x-build: &build-settings
  build:
    context: .
    dockerfile: docker/Dockerfile.run  # Use the specified Dockerfile.
  image: lunanightbyte/ml-process:v0.0.3
  restart: "no"  # Disable container auto-restart.

services:
  ML-build:
    <<: *build-settings

  ML-process:
    <<: *default-settings
    container_name: ml-processor
    volumes:
      - ./local:/usr/src/app               # Mount local directory for application files.
      - ./output:/usr/src/app/data/output:rw  # Output directory with read/write permissions.
      - ./datasets:/usr/src/app/datasets:rw  # Datasets directory with read/write permissions.
      - ./models:/usr/src/app/data/models:ro  # Models directory with read-only permissions.
      - ./input:/usr/src/app/data/input:ro    # Input directory with read-only permissions.

    # Uncomment the following for Linux webcam support:
    # devices:
    #   - /dev/video0:/dev/video0
