name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract Git Tag
        id: extract-tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "Using tag: $TAG"

      - name: Sanitize Git Tag
        id: sanitize-tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          SANITIZED_TAG=$(echo "$TAG" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g')
          echo "SANITIZED_TAG=${SANITIZED_TAG}" >> $GITHUB_ENV
          echo "Sanitized tag: $SANITIZED_TAG"

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=lunanightbyte/ml-process
          TAG=${{ env.SANITIZED_TAG }}
          
          # Build with sanitized tag and latest
          docker build -f docker/Dockerfile.run -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
